import { StyleSheet } from 'react-native';

export const chatSellerStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#fff" },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#DADCE0",
    },
    headerLeft: { flexDirection: "row", alignItems: "center" },
    avatar: { width: 40, height: 40, borderRadius: 20, marginLeft: 12, marginRight: 8 },
    onlineDot: {
        position: "absolute",
        bottom: 0,
        right: 6,
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: "#4CD964",
        borderWidth: 2,
        borderColor: "#fff",
    },
    name: { fontSize: 16, fontWeight: "600" },
    status: { fontSize: 13, color: "#333", opacity: 0.6 },

    messagesContainer: { padding: 12 },
    messageRow: { marginBottom: 12 },
    leftAlign: { alignItems: "flex-start" },
    rightAlign: { alignItems: "flex-end" },
    bubble: {
        maxWidth: "75%",
        paddingVertical: 10,
        paddingHorizontal: 14,
        borderRadius: 12,
    },
    myBubble: { backgroundColor: "#0ED3AF", borderTopRightRadius: 0 },
    shopBubble: { backgroundColor: "#0000000F", borderTopLeftRadius: 0 },
    messageText: { fontSize: 15, lineHeight: 20 },
    myText: { color: "#fff" },
    shopText: { color: "#000" },
    time: { fontSize: 11, color: "#999", marginTop: 4 },
    dateSeparator: {
        alignItems: 'center',
        marginVertical: 16,
    },
    dateSeparatorText: {
        fontSize: 12,
        color: '#666',
        backgroundColor: '#F0F0F0',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
        fontWeight: '500',
    },

    inputRow: {
        flexDirection: "row",
        alignItems: "center",
        padding: 12,
        backgroundColor: "#fff",
    },
    input: {
        flex: 1,
        marginHorizontal: 12,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 20,
        backgroundColor: "#0000000F",
        fontSize: 15,
    },
    sendButton: {
        backgroundColor: "#FBBC05",
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: "center",
        justifyContent: "center",
    },
});
