import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: { flex: 1, backgroundColor: "#F8F9FA" },

    header: {
        backgroundColor: "#F59E0B",
        paddingTop: 12,
        paddingHorizontal: 16,
        paddingBottom: 24,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 1,
        position: "relative",
        overflow: "hidden",
    },
    backButton: {
        position: "relative",
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "rgba(255, 255, 255, 0.25)",
        justifyContent: "center",
        alignItems: "center",
    },
    headerDecoration: {
        position: "absolute",
        top: -80,
        right: -80,
        width: 240,
        height: 240,
        borderRadius: 120,
        backgroundColor: "rgba(255, 255, 255, 0.12)",
    },
    headerDecoration2: {
        position: "absolute",
        bottom: -40,
        left: -40,
        width: 180,
        height: 180,
        borderRadius: 90,
        backgroundColor: "rgba(255, 255, 255, 0.08)",
    },
    headerTop: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 16,
    },
    headerTitle: {
        color: "#fff",
        fontSize: 20,
        fontWeight: "700",
        flex: 1,
        textAlign: "center",
        textShadowColor: "rgba(0, 0, 0, 0.15)",
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
    },

    shopInfo: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 16,
        marginTop: 48,
        paddingHorizontal: 4,
    },
    avatar: {
        width: 88,
        height: 88,
        borderRadius: 44,
        backgroundColor: "#fff",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 10,
    },
    avatarContainer: {
        position: "relative",
        zIndex: 2,
    },
    shopTextContainer: { 
        marginLeft: 16, 
        flex: 1, 
        zIndex: 2,
        justifyContent: "center",
    },
    titleRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 6,
        flexWrap: "wrap",
    },
    shopName: {
        fontSize: 22,
        fontWeight: "800",
        color: "#fff",
        marginRight: 10,
        textShadowColor: "rgba(0, 0, 0, 0.2)",
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
        letterSpacing: 0.5,
    },
    ratingBadge: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255, 255, 255, 0.25)",
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
    },
    ratingText: {
        fontSize: 12,
        color: "#fff",
        fontWeight: "700",
        marginLeft: 4,
    },
    subText: {
        fontSize: 13,
        color: "rgba(255, 255, 255, 0.95)",
        lineHeight: 18,
        fontWeight: "500",
    },
    statsRow: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 8,
        flexWrap: "wrap",
        gap: 6,
    },
    statItem: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 12,
        marginRight: 6,
    },
    statIcon: {
        marginRight: 5,
    },
    statText: {
        fontSize: 12,
        color: "#fff",
        fontWeight: "700",
    },

    buttonRow: {
        flexDirection: "row",
        justifyContent: "flex-end",
        gap: 12,
        paddingHorizontal: 4,
        marginTop: 4,
    },
    followButton: {
        backgroundColor: "#fff",
        borderRadius: 24,
        paddingVertical: 10,
        paddingHorizontal: 20,
        flexDirection: "row",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
        elevation: 8,
        minWidth: 120,
        justifyContent: "center",
        borderWidth: 0,
    },
    followingButton: {
        backgroundColor: "#fff",
    },
    followButtonText: {
        color: "#FBBC05",
        fontWeight: "800",
        fontSize: 14,
        marginLeft: 6,
    },
    followingButtonText: {
        color: "#FBBC05",
        fontWeight: "700",
    },
    chatButton: {
        backgroundColor: "rgba(255, 255, 255, 0.95)",
        borderRadius: 24,
        paddingVertical: 10,
        paddingHorizontal: 20,
        flexDirection: "row",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
        elevation: 8,
        minWidth: 100,
        justifyContent: "center",
    },
    chatButtonText: {
        color: "#0ED3AF",
        fontWeight: "800",
        fontSize: 14,
        marginLeft: 6,
    },

    tabs: {
        flexDirection: "row",
        justifyContent: "space-around",
        marginTop: 16,
        backgroundColor: "#fff",
        borderBottomWidth: 1,
        borderColor: "#E8E8E8",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 3,
        elevation: 3,
        paddingHorizontal: 8,
    },
    tab: {
        flex: 1,
        alignItems: "center",
        paddingVertical: 14,
        position: "relative",
    },
    tabDivider: {
        position: "absolute",
        width: 1,
        height: "60%",
        backgroundColor: "#E0E0E0",
        left: "50%",
        top: "20%",
    },
    tabText: {
        color: "#999",
        fontWeight: "600",
        fontSize: 15,
    },
    tabBadge: {
        backgroundColor: "#FBBC05",
        borderRadius: 10,
        paddingHorizontal: 6,
        paddingVertical: 2,
        marginLeft: 6,
        minWidth: 20,
        alignItems: "center",
    },
    tabBadgeText: {
        color: "#fff",
        fontSize: 11,
        fontWeight: "700",
    },
    activeTab: {
        borderBottomWidth: 3,
        borderBottomColor: "#FBBC05",
    },
    activeTabText: {
        color: "#FBBC05",
        fontWeight: "700",
        fontSize: 15,
    },

    productsList: {
        paddingTop: 10,
        paddingBottom: 20,
    },
    columnWrapper: {
        justifyContent: 'space-between',
        paddingHorizontal: 12,
    },
    productCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 10,
        marginVertical: 6,
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    imageWrapper: {
        position: "relative",
        width: "100%",
        height: 140,
        borderRadius: 10,
        overflow: "hidden",
        marginBottom: 6,
    },
    productImage: {
        width: "100%",
        height: 140,
        borderRadius: 8,
    },
    discountBadge: {
        position: "absolute",
        top: 10,
        left: 10,
        backgroundColor: "#FF3B30",
        borderRadius: 6,
        paddingHorizontal: 8,
        paddingVertical: 4,
        zIndex: 1,
        shadowColor: "#FF3B30",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4,
    },
    discountBadgeText: {
        color: "#FFF", 
        fontSize: 11, 
        fontWeight: "700",
        letterSpacing: 0.3,
    },
    productName: {
        marginTop: 4,
        fontSize: 14,
        fontWeight: "500",
        marginBottom: 4,
    },
    priceRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        marginTop: 4,
    },
    productPrice: {
        color: "#E53935",
        fontWeight: "700",
        fontSize: 18,
    },
    oldPrice: {
        textDecorationLine: "line-through",
        color: "#999",
        fontSize: 12,
    },
    metaRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 4,
    },
    soldLabel: {
        fontSize: 12,
        color: "#666",
    },
    rating: {
        fontSize: 12,
        color: "#666",
    },

    categoryCard: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#fff",
        padding: 18,
        borderRadius: 14,
        marginBottom: 14,
        marginHorizontal: 8,
        elevation: 3,
        borderWidth: 1,
        borderColor: "#F0F0F0",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
    },
    categoryIcon: {
        width: 48,
        height: 48,
        marginRight: 16,
        borderRadius: 10,
        backgroundColor: "#FFF9E6",
        justifyContent: "center",
        alignItems: "center",
    },
    categoryName: {
        fontSize: 16,
        fontWeight: "600",
        color: "#333",
        flex: 1,
    },
    categoryArrow: {
        marginLeft: 8,
    },

    emptyContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingVertical: 100,
        paddingHorizontal: 40,
        backgroundColor: "#fff",
        marginHorizontal: 16,
        marginTop: 20,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#F0F0F0",
        borderStyle: "dashed",
    },
    emptyIcon: {
        marginBottom: 20,
        opacity: 0.4,
    },
    emptyText: {
        fontSize: 17,
        color: "#999",
        fontWeight: "600",
        textAlign: "center",
        marginBottom: 4,
    },
    emptySubText: {
        fontSize: 14,
        color: "#BBB",
        marginTop: 8,
        textAlign: "center",
        lineHeight: 20,
    },

    descriptionContainer: {
        backgroundColor: "#fff",
        marginHorizontal: 16,
        marginTop: 20,
        padding: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 3,
    },
    descriptionTitle: {
        fontSize: 17,
        fontWeight: "800",
        color: "#333",
        marginBottom: 4,
        flexDirection: "row",
        alignItems: "center",
    },
    descriptionTitleIcon: {
        marginRight: 8,
        marginBottom: 4
    },
    descriptionText: {
        fontSize: 15,
        color: "#666",
        lineHeight: 22
    },
});

