import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: { flex: 1, backgroundColor: "#F8F9FA" },

    header: {
        backgroundColor: "#FBBC05",
        paddingTop: 16,
        paddingHorizontal: 12,
        paddingBottom: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 8,
        position: "relative",
        overflow: "hidden",
    },
    backButton: {
        position: "absolute",
        top: 16,
        left: 12,
        zIndex: 3,
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: "rgba(0, 0, 0, 0.1)",
        justifyContent: "center",
        alignItems: "center",
    },
    headerDecoration: {
        position: "absolute",
        top: -50,
        right: -50,
        width: 200,
        height: 200,
        borderRadius: 100,
        backgroundColor: "rgba(255, 255, 255, 0.1)",
    },
    headerDecoration2: {
        position: "absolute",
        bottom: -30,
        left: -30,
        width: 150,
        height: 150,
        borderRadius: 75,
        backgroundColor: "rgba(255, 255, 255, 0.08)",
    },
    headerTop: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
    },
    headerTitle: {
        color: "#fff",
        fontSize: 20,
        fontWeight: "700",
        flex: 1,
        textAlign: "center",
        textShadowColor: "rgba(0, 0, 0, 0.1)",
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },

    shopInfo: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 20,
        marginLeft: 36,
    },
    avatar: {
        width: 80,
        height: 80,
        borderRadius: 50,
        backgroundColor: "#fff",
        borderWidth: 5,
        borderColor: "#fff",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
        elevation: 8,
    },
    avatarContainer: {
        position: "relative",
        zIndex: 2,
    },
    shopTextContainer: { marginLeft: 18, flex: 1, zIndex: 2 },
    titleRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 8,
        flexWrap: "wrap",
    },
    shopName: {
        fontSize: 24,
        fontWeight: "900",
        color: "#fff",
        marginRight: 12,
        textShadowColor: "rgba(0, 0, 0, 0.15)",
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 3,
        letterSpacing: 0.3,
    },
    ratingBadge: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255, 255, 255, 0.15)",
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 10,
    },
    ratingText: {
        fontSize: 11,
        color: "#fff",
        fontWeight: "600",
        marginLeft: 4,
    },
    subText: {
        fontSize: 14,
        color: "#fff",
        opacity: 0.95,
        lineHeight: 20,
    },
    statsRow: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 6,
        flexWrap: "wrap",
        gap: 8,
    },
    statItem: {
        flexDirection: "row",
        alignItems: "center",
        marginRight: 12,
        marginTop: 4,
        backgroundColor: "rgba(255, 255, 255, 0.15)",
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 10,
    },
    statIcon: {
        marginRight: 4,
    },
    statText: {
        fontSize: 11,
        color: "#fff",
        fontWeight: "600",
    },

    buttonRow: {
        flexDirection: "row",
        justifyContent: "flex-end",
        gap: 10,
    },
    followButton: {
        backgroundColor: "#fff",
        borderRadius: 20,
        paddingVertical: 8,
        paddingHorizontal: 16,
        flexDirection: "row",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 6,
        minWidth: 110,
        justifyContent: "center",
        borderWidth: 2,
        borderColor: "rgba(255, 255, 255, 0.3)",
    },
    followingButton: {
        backgroundColor: "#E8E8E8",
        borderColor: "#D0D0D0",
    },
    followButtonText: {
        color: "#FBBC05",
        fontWeight: "700",
        fontSize: 13,
        marginLeft: 4,
    },
    followingButtonText: {
        color: "#666",
    },
    chatButton: {
        backgroundColor: "#0ED3AF",
        borderRadius: 20,
        paddingVertical: 8,
        paddingHorizontal: 16,
        flexDirection: "row",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 6,
        minWidth: 90,
        justifyContent: "center",
        borderWidth: 2,
        borderColor: "rgba(255, 255, 255, 0.3)",
    },
    chatButtonText: {
        color: "#fff",
        fontWeight: "700",
        fontSize: 13,
        marginLeft: 4,
    },

    tabs: {
        flexDirection: "row",
        justifyContent: "space-around",
        marginTop: 16,
        backgroundColor: "#fff",
        borderBottomWidth: 1,
        borderColor: "#E8E8E8",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 3,
        elevation: 3,
        paddingHorizontal: 8,
    },
    tab: {
        flex: 1,
        alignItems: "center",
        paddingVertical: 14,
        position: "relative",
    },
    tabDivider: {
        position: "absolute",
        width: 1,
        height: "60%",
        backgroundColor: "#E0E0E0",
        left: "50%",
        top: "20%",
    },
    tabText: {
        color: "#999",
        fontWeight: "600",
        fontSize: 15,
    },
    tabBadge: {
        backgroundColor: "#FBBC05",
        borderRadius: 10,
        paddingHorizontal: 6,
        paddingVertical: 2,
        marginLeft: 6,
        minWidth: 20,
        alignItems: "center",
    },
    tabBadgeText: {
        color: "#fff",
        fontSize: 11,
        fontWeight: "700",
    },
    activeTab: {
        borderBottomWidth: 3,
        borderBottomColor: "#FBBC05",
    },
    activeTabText: {
        color: "#FBBC05",
        fontWeight: "700",
        fontSize: 15,
    },

    productsList: {
        paddingTop: 10,
        paddingBottom: 20,
    },
    columnWrapper: {
        justifyContent: 'space-between',
        paddingHorizontal: 12,
    },
    productCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 10,
        marginVertical: 6,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    imageWrapper: {
        position: "relative",
        width: "100%",
        height: 140,
        borderRadius: 10,
        overflow: "hidden",
        marginBottom: 6,
    },
    productImage: {
        width: "100%",
        height: 140,
        borderRadius: 8,
    },
    discountBadge: {
        position: "absolute",
        top: 6,
        left: 6,
        backgroundColor: "#FFA000",
        borderRadius: 4,
        paddingHorizontal: 4,
        paddingVertical: 2,
        zIndex: 1,
    },
    discountBadgeText: {
        color: "#fff",
        fontSize: 12,
        fontWeight: "700",
    },
    productName: {
        marginTop: 4,
        fontSize: 14,
        fontWeight: "500",
        marginBottom: 4,
    },
    priceRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        marginTop: 4,
    },
    productPrice: {
        color: "#E53935",
        fontWeight: "700",
        fontSize: 14,
    },
    oldPrice: {
        textDecorationLine: "line-through",
        color: "#999",
        fontSize: 12,
    },
    metaRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 4,
    },
    soldLabel: {
        fontSize: 12,
        color: "#666",
    },
    rating: {
        fontSize: 12,
        color: "#666",
    },

    categoryCard: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#fff",
        padding: 18,
        borderRadius: 14,
        marginBottom: 14,
        marginHorizontal: 8,
        elevation: 3,
        borderWidth: 1,
        borderColor: "#F0F0F0",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
    },
    categoryIcon: {
        width: 48,
        height: 48,
        marginRight: 16,
        borderRadius: 10,
        backgroundColor: "#FFF9E6",
        justifyContent: "center",
        alignItems: "center",
    },
    categoryName: {
        fontSize: 16,
        fontWeight: "600",
        color: "#333",
        flex: 1,
    },
    categoryArrow: {
        marginLeft: 8,
    },

    emptyContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingVertical: 100,
        paddingHorizontal: 40,
        backgroundColor: "#fff",
        marginHorizontal: 16,
        marginTop: 20,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#F0F0F0",
        borderStyle: "dashed",
    },
    emptyIcon: {
        marginBottom: 20,
        opacity: 0.4,
    },
    emptyText: {
        fontSize: 17,
        color: "#999",
        fontWeight: "600",
        textAlign: "center",
        marginBottom: 4,
    },
    emptySubText: {
        fontSize: 14,
        color: "#BBB",
        marginTop: 8,
        textAlign: "center",
        lineHeight: 20,
    },

    descriptionContainer: {
        backgroundColor: "#fff",
        marginHorizontal: 16,
        marginTop: 20,
        padding: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 3,
    },
    descriptionTitle: {
        fontSize: 17,
        fontWeight: "800",
        color: "#333",
        marginBottom: 4,
        flexDirection: "row",
        alignItems: "center",
    },
    descriptionTitleIcon: {
        marginRight: 8,
        marginBottom: 4
    },
    descriptionText: {
        fontSize: 15,
        color: "#666",
        lineHeight: 22
    },
});

