import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#FFF",
    },
    header: {
        paddingRight: 16,
        paddingVertical: 16,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    searchBarContainer: {
        flex: 1,
        marginRight: 16,
    },
    cartButton: {
        width: 40,
        justifyContent: "center",
        alignItems: "center",
    },
    heroBanner: {
        marginBottom: 24,
    },
    heroContent: {
        position: "relative",
        width: "100%",
        height: 180,
        marginBottom: 4,
    },
    heroBackgroundImage: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: "100%",
        resizeMode: "cover",
    },
    heroTextContainer: {
        position: "absolute",
        top: 60,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 2,
        padding: 20,
    },
    heroSubtitle: {
        fontSize: 10,
        color: "gray",
        marginTop: 20,
        marginBottom: 10,
        marginLeft: 8,
        lineHeight: 12,
        zIndex: 3,
    },
    heroButton: {
        backgroundColor: "#FBBC05",
        paddingHorizontal: 8,
        paddingVertical: 6,
        borderRadius: 8,
        alignSelf: "flex-start",
        zIndex: 3,
        marginLeft: 8,
    },
    heroButtonText: {
        color: "#FFFFFF",
        fontSize: 11,
        fontWeight: "600",
        textAlign: "center",
    },
    section: {
        marginBottom: 18,
    },
    sectionHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 16,
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 19,
        fontWeight: "bold",
        color: "#000",
    },
    viewAllText: {
        fontSize: 14,
        color: "#FBBC05",
        fontWeight: "600",
    },
    categoriesList: {
        paddingLeft: 16,
    },
    categoryItem: {
        alignItems: "center",
        marginRight: 16,
        width: 70,
    },
    categoryIconContainer: {
        width: 66,
        height: 80,
        backgroundColor: "#FFFFFF",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "#EEEEEE",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 8,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 0,
        },
        shadowOpacity: 0.15,
        shadowRadius: 6,
        elevation: 5,
    },
    categoryIcon: {
        width: 36,
        height: 36,
        resizeMode: "contain",
        marginBottom: 8,
    },
    categoryText: {
        fontSize: 13,
        color: "#000",
        fontWeight: "600",
        textAlign: "center",
    },
    productsList: {
        paddingLeft: 16,
        paddingRight: 4,
    },
    productWrapper: {
        width: 160,
        marginRight: 12,
    },
    storesList: {
        paddingLeft: 16,
        paddingRight: 4,
        paddingBottom: 8,
    },
    storeItem: {
        backgroundColor: "#FFFAE8",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#ddd",
        padding: 12,
        marginRight: 12,
        width: 160,
        alignItems: "center",
    },
    storeAvatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        marginBottom: 8,
    },
    storeInfo: {
        alignItems: "center",
        width: "100%",
    },
    storeName: {
        fontSize: 14,
        fontWeight: "600",
        color: "#000",
        textAlign: "center",
        marginBottom: 6,
    },
    followButton: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        marginBottom: 8,
        alignSelf: "center",
    },
    followButtonText: {
        fontSize: 11,
        fontWeight: "600",
    },
    storeStatRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 4,
        gap: 8,
    },
    storeStatText: {
        fontSize: 11,
        color: "#7F8C8D",
        textAlign: "center",
    },
});
