import { StyleSheet } from 'react-native';

export const categoriesStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F8F8F8",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#FFFFFF",
        borderBottomWidth: 1,
        borderBottomColor: "#F0F0F0",
        paddingHorizontal: 16,
        paddingVertical: 16,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: "700",
        marginLeft: 16,
        flex: 1,
        color: "#1A1A1A",
        paddingTop: 16,
    },
    headerContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    categoryContainer: {
        paddingTop: 6,
    },
    categorySection: {
        marginBottom: 16,
        marginTop: 16,
        paddingHorizontal: 16,
    },
    categoryHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 16,
        //backgroundColor: "#FFF9E6",
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    categoryIcon: {
        width: 36,
        height: 36,
        resizeMode: "contain",
        marginRight: 10,
    },
    categoryTitle: {
        fontSize: 17,
        fontWeight: "700",
        color: "#FBBC05",
    },
    childContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        gap: 10,
    },
    childCard: {
        width: "47%",
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        paddingVertical: 16,
        paddingHorizontal: 12,
        marginBottom: 10,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 10,
        minHeight: 140,
        justifyContent: "center",
        //borderColor: "#FFF44F",
        //borderWidth: 1,
    },
    childImage: {
        width: 70,
        height: 70,
        resizeMode: "contain",
        marginBottom: 12,
    },
    childText: {
        fontSize: 14,
        fontWeight: "500",
        color: "#1A1A1A",
        textAlign: "center",
    },
});