import { StyleSheet } from 'react-native';

export const productCardStyles = StyleSheet.create({
    card: {
        backgroundColor: "#FFFAE8",
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 12,
        marginBottom: 12,
        overflow: "hidden",
        width: "48%",
        minHeight: 340,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 10,
    },
    horizontalCard: {
        width: "100%",
        minHeight: 340,
    },
    discountBadge: {
        position: "absolute",
        top: 10,
        left: 10,
        backgroundColor: "#FF3B30",
        borderRadius: 6,
        paddingHorizontal: 8,
        paddingVertical: 4,
        zIndex: 1,
        shadowColor: "#FF3B30",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4,
    },
    discountText: {
        color: "#FFF",
        fontSize: 11,
        fontWeight: "700",
        letterSpacing: 0.3,
    },
    image: {
        width: "100%",
        height: 170,
        backgroundColor: "#F5F5F5",
    },

    info: {
        padding: 12,
        flex: 1,
        justifyContent: 'space-between',
        backgroundColor: "#FFFAE8",
    },
    mainContent: {
        flex: 1,
    },
    shopRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 8,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: "#F0F0F0",
    },
    shopAvatar: {
        width: 28,
        height: 28,
        borderRadius: 14,
        borderWidth: 1.5,
        borderColor: "#E8E8E8",
    },
    shopName: {
        fontSize: 12,
        fontWeight: "600",
        color: "#1A1A1A",
    },
    sold: {
        fontSize: 10,
        color: "#8E8E93",
        marginTop: 2,
    },

    metaRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 8,
    },
    categoryText: {
        fontSize: 10,
        fontWeight: "500",
        color: "#007AFF",
        backgroundColor: "#E3F2FD",
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 4,
        overflow: "hidden",
        maxWidth: "65%",
    },
    ratingRow: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#FFF9E6",
        paddingHorizontal: 6,
        paddingVertical: 3,
        borderRadius: 4,
    },
    ratingText: {
        fontSize: 11,
        color: "#1A1A1A",
        marginLeft: 4,
        fontWeight: "600",
    },

    productName: {
        fontSize: 14,
        fontWeight: "500",
        marginBottom: 6,
        lineHeight: 20,
        color: "#1A1A1A",
        minHeight: 40,
    },
    tagline: {
        fontSize: 10,
        color: "#FF6B35",
        fontWeight: "500",
        marginBottom: 8,
        backgroundColor: "#FFF5F0",
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 4,
        alignSelf: "flex-start",
    },

    priceRow: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 8,
        paddingTop: 8,
        borderTopWidth: 1,
        borderTopColor: "#F0F0F0",
    },
    price: {
        fontSize: 18,
        fontWeight: "700",
        color: "#FF3B30",
        marginRight: 8,
    },
    oldPrice: {
        fontSize: 12,
        color: "#8E8E93",
        textDecorationLine: "line-through",
        fontWeight: "400",
    },
});