import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    zIndex: 10,
    backgroundColor: '#F8FAFC',
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000',
  },
  placeholder: {
    width: 32,
  },
  backgroundContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '100%',
    zIndex: 1,
  },
  gradientBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 300,
    backgroundColor: '#FBBC05',
    opacity: 0.1,
  },
  backgroundCircle1: {
    position: 'absolute',
    top: -80,
    right: -120,
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: '#FBBC05',
    opacity: 0.05,
  },
  backgroundCircle2: {
    position: 'absolute',
    top: 100,
    left: -100,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: '#3B82F6',
    opacity: 0.03,
  },
  backgroundCircle3: {
    position: 'absolute',
    bottom: -50,
    right: -80,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: '#FBBC05',
    opacity: 0.04,
  },
  scrollView: {
    flex: 1,
    zIndex: 5,
  },
  heroSection: {
    alignItems: 'flex-start',
    paddingHorizontal: 20,
    paddingVertical: 30,
    marginBottom: 10,
  },
  heroIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FBBC05',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#FBBC05',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  mainTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#1F2937',
    textAlign: 'left',
    marginBottom: 8,
    alignSelf: 'flex-start',
  },
  subtitle: {
    fontSize: 16,
    color: '#6B7280',
    textAlign: 'left',
    lineHeight: 22,
    alignSelf: 'flex-start',
  },
  titleUnderline: {
    width: 80,
    height: 4,
    backgroundColor: '#FBBC05',
    borderRadius: 2,
    marginTop: 12,
    alignSelf: 'flex-start',
  },
  itemsContainer: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  termItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    overflow: 'hidden',
  },
  itemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  iconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FEF3C7',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 2,
    borderColor: '#FBBC05',
  },
  itemIcon: {
    width: 28,
    height: 28,
  },
  textContainer: {
    flex: 1,
    marginRight: 12,
    alignItems: 'flex-start',
  },
  itemTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
    lineHeight: 24,
    marginBottom: 4,
    textAlign: 'left',
  },
  itemDescription: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
    textAlign: 'left',
  },
  chevronContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pressableEffect: {
    transform: [{ scale: 0.98 }],
  },
  expandedContent: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  contentText: {
    fontSize: 14,
    lineHeight: 22,
    color: '#374151',
    textAlign: 'left',
  },
});